spring:
  application:
    name: auth-service
    domain: localhost
    frontend-url: http://localhost:8080/auth
  datasource:
    url: test
    username: test
    password: test
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  jwt:
    secret: test-secret-jwt-string
    expiration:
      access-minutes: 15
      refresh-days: 30
  main:
    allow-circular-references: true
  flyway:
    enabled: false

server:
  servlet:
    context-path: /auth

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    org.testcontainers: WARN