spring:
  application:
    name: auth-service
    domain: ${APP_DOMAIN}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    expiration:
      access-minutes: ${JWT_ACCESS_MINUTES}
      refresh-days: ${JWT_REFRESH_DAYS}
  main:
    allow-circular-references: true
  flyway:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}

server:
  servlet:
    context-path: /auth
